"""Core module for the AKM framework."""

from akm.core.config import AKMConfig, load_config
from akm.core.exceptions import (
    AKMError,
    BackendNotAvailableError,
    ConfigurationError,
    ConnectionError,
    EmbeddingError,
    EntityNotFoundError,
    GNNError,
    IngestionError,
    LinkNotFoundError,
    PluginError,
    QueryError,
    RelationshipNotFoundError,
    SchemaError,
    ValidationError,
)
from akm.core.interfaces import (
    ChunkingStrategy,
    DataConnector,
    DomainTransformer,
    EmbeddingModel,
    GNNModel,
    GraphBackend,
    LLMProvider,
    Plugin,
    VectorBackend,
)
from akm.core.models import (
    AKMBaseModel,
    Chunk,
    ContextItem,
    Document,
    DomainSchema,
    Entity,
    EntityType,
    EntityTypeDefinition,
    ExtractedEntity,
    ExtractedRelationship,
    GraphData,
    Link,
    LinkStatus,
    LinkWeight,
    NodeEmbeddings,
    QueryResult,
    RawDocument,
    Relationship,
    RelationshipType,
    RelationshipTypeDefinition,
    SearchResult,
    TrainingResult,
    TraversalResult,
)

__all__ = [
    # Config
    "AKMConfig",
    "load_config",
    # Exceptions
    "AKMError",
    "BackendNotAvailableError",
    "ConfigurationError",
    "ConnectionError",
    "EmbeddingError",
    "EntityNotFoundError",
    "GNNError",
    "IngestionError",
    "LinkNotFoundError",
    "PluginError",
    "QueryError",
    "RelationshipNotFoundError",
    "SchemaError",
    "ValidationError",
    # Interfaces
    "ChunkingStrategy",
    "DataConnector",
    "DomainTransformer",
    "EmbeddingModel",
    "GNNModel",
    "GraphBackend",
    "LLMProvider",
    "Plugin",
    "VectorBackend",
    # Models
    "AKMBaseModel",
    "Chunk",
    "ContextItem",
    "Document",
    "DomainSchema",
    "Entity",
    "EntityType",
    "EntityTypeDefinition",
    "ExtractedEntity",
    "ExtractedRelationship",
    "GraphData",
    "Link",
    "LinkStatus",
    "LinkWeight",
    "NodeEmbeddings",
    "QueryResult",
    "RawDocument",
    "Relationship",
    "RelationshipType",
    "RelationshipTypeDefinition",
    "SearchResult",
    "TrainingResult",
    "TraversalResult",
]
